apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: squidproxy-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx-internal"
spec:
  rules:
  - host: proxy-test.hodc-acp.homeoffice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: squidproxy-service
          servicePort: 3129
